CREATE TABLE uk_vehicles (
    Accident_Index VARCHAR(20),
    Vehicle_Reference INT,
    Vehicle_Type INT,
    Towing_and_Articulation INT,
    Vehicle_Manoeuvre INT,
    Vehicle_Location_Restricted_Lane INT,
    Junction_Location INT,
    Skidding_and_Overturning INT,
    Hit_Object_in_Carriageway INT,
    Vehicle_Leaving_Carriageway INT,
    Hit_Object_off_Carriageway INT,
    First_Point_of_Impact INT,
    Was_Vehicle_Left_Hand_Drive BIT,
    Journey_Purpose_of_Driver INT,
    Sex_of_Driver INT,
    Age_of_Driver INT,
    Age_Band_of_Driver INT,
    Engine_Capacity_CC INT,
    Propulsion_Code INT,
    Age_of_Vehicle INT,
    Driver_IMD_Decile INT,
    Driver_Home_Area_Type INT,
    Vehicle_IMD_Decile INT,
   -- FOREIGN KEY (Accident_Index) REFERENCES uk_accidents(Accident_Index)
);
